server:
  port: 8083

# database setting
spring:
  datasource:
    url: jdbc:mariadb://yoult.iptime.org:3428/foodietree
    username: root
    password: foodie1969!@
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    # DBMS dialect setting
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl 수행시 어떻게 처리할지...,
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # SQL 로그 줄맞춤 해주는 설정
    database: mysql

# log level setting
logging:
  level:
    root: info
    com:
      foodietree: debug
    org:
      hibernate:
        SQL: debug





